version: '3.9'
networks:
  local_prjctnet:
    external: true

services:
  backend:
    build: .
    image: harbor.cubexs.dev/prjctrepo/backend

  backend-run:
    image: node:18.12.0-alpine3.15
    container_name: backend
    env_file: ./.env
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./src:/app/src
    networks:
      - local_prjctnet
    command: ['sh', '-c', 'cd /app && npm install && npm run dev']

  backend-unit-tests:
    image: node:18.12.0-alpine3.15
    container_name: backend-test
    env_file: ./.env
    volumes:
      - .:/app
    command: ['sh', '-c', 'cd /app && npm install && npm run test']

  backend-ci-unit-tests:
    image: node:18.12.0-alpine3.15
    container_name: backend-ci-test
    env_file: ./.env
    volumes:
      - .:/app
    command: ['sh', '-c', 'cd /app && npm install && npm run test-ci']
